services:
  web:
    build:
      context: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"  # 👈 changed to 3001 since grafana uses 3000

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.local
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  promethus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - 3001:3000
      restart: unless-stopped
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - ./grafana:/etc/grafana/provisioning/datasources
volumes:
  minio_data:
